export const allArmsList = {
	arms: [
		'Glock-17',
		'Glock knives',
		'MSMC',
		'AK - 63D 7.62x39mm assault rifle',
		'Heckler & Koch MP5 submachine gun',
		'Beretta AR70 assault rifle',
		'Franchi SPAS-15 Combat shotgun',
		'CornerShot guns',
		'TriCa 7.62x39 mm Carbine',
		'M249 Light machine gun',
		'Heckler & Koch MSG90 sniper rifle',
		'Heckler & Koch PSG1 A1 sniper rifle',
		'IWI Tavor X95 bullpup rifle',
		'Barrett Model 98B Sniper rifle',
		'SIG MPX Submachine gun',
		'FN Herstal F2000',
		'FN SCAR',
		'FN P90',
		'FN Herstal Five-seveN',
		'IOF Modern Sub Machine Carbine',
		'Khukri',
		'M9 Bayonet',
		'Glock knife',
		'Naga Dao',
		'Pistol Auto 9mm 1A-semi-automatic pistol',
		'Glock 17-Semi-automatic pistol',
		'Gaston Glock-Semi-automatic pistol',
		'Glock P80-Semi-automatic pistol',
		'Glock 22-Semi-automatic pistol',
		'Glock 26-Semi-automatic pistol',
		'Glock 30-Semi-automatic pistol',
		'Glock 19-Semi-automatic pistol',
		'Glock 23-Semi-automatic pistol',
		'Glock 27-Semi-automatic pistol',
		'Glock 20-Semi-automatic pistol',
		'Beretta Px4 Storm-semi-automatic pistol',
		'Beretta 92-semi-automatic pistol',
		'Beretta 8000 series-semi-automatic pistol',
		'ShootEdge-CornerShot',
		'DRDO CSWS (CornerShot Weapon System)',
		'12 Bore PAG-Pump action Shotgun',
		'Micro-Uzi-Machine pistol',
		'Heckler & Koch MP5-Submachine gun',
		'Brügger & Thomet MP9-Submachine gun',
		'SAF Carbine 2A1-Submachine gun',
		'1B1 INSAS-Assault rifle',
		'AK-203-Assault rifle',
		'SIG 716i-Battle rifle',
		'FN SCAR L-Assault rifle',
		'FN SCAR H--Battle rifle',
		'IWI X95-Assault rifle',
		'IMI Tavor TAR-21-Assault rifle',
		'T91 assault rifle-Assault rifle',
		'M4 carbine',
		'AR-M1',
		'AKM',
		'AK-47-Assault rifle',
		'MPi-KMS-72-Assault rifle',
		'Vz.58-Assault rifle',
		'Dragunov SVD-Sniper rifle',
		'IMI Galil 7.62 Sniper-Sniper rifle',
		'Heckler & Koch PSG1-Sniper rifle',
		'Mauser SP66-Sniper rifle',
		'SIG Sauer SSG 3000-Sniper rifle',
		'Sako TRG 42-Sniper rifle',
		'Beretta Scorpio TGT-Sniper rifle',
		'Barrett M82-Anti-material rifle',
		'Barrett M95-Anti-material rifle',
		'OSV-96-Anti-material rifle',
		'Vidhwansak-Anti-material rifle',
		'IMI Negev NG7-General-purpose machine gun',
		'MG 2A1-General-purpose machine gun',
		'MG 5A-General-purpose machine gun',
		'MG 6A-General-purpose machine gun',
		'Mk 48 -General-purpose machine gun',
		'PK-General-purpose machine gun',
		'FN Minimi-Light machine gun',
		'IMI Negev NG5-Light machine gun',
		'NSV machine gun-Heavy machine gun',
		'M2 Browning-Heavy machine gun',
		'MSMC-Submachine gun',
		'ASMI-Submachine gun',
		'Shivalik-Hand grenade',
		'ARDE 40MM UBGL-Grenade launcher (40mm)',
		'Multi Grenade Launcher 40mm',
		'AGS-30-Automatic grenade launcher',
		'AT4CS AST-Recoilless gun (84mm)',
		'Carl Gustav RCL M2/M3/M4-Recoilless rifle (84mm)',
		'B-300 Shipon-Anti-tank rocket (82mm)',
		'RPO-A Shmel-Thermobaric rocket launcher (93mm)',
		'51mm E1 mortar-Mortar',
		'L16 81mm mortar'
	]
};
