# Generated by Django 4.2.2 on 2023-09-22 15:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('phone', models.CharField(max_length=14, unique=True)),
                ('role', models.CharField(default='passenger', max_length=55)),
                ('name', models.CharField(blank=True, max_length=55, null=True)),
                ('email', models.EmailField(blank=True, max_length=255, null=True)),
                ('image_url', models.URLField(blank=True, null=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('fcm_token', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'Users',
            },
        ),
        migrations.CreateModel(
            name='BandobasOfficer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fcm_token', models.CharField(default='officer_not_registered', max_length=255)),
                ('device_id', models.CharField(default='officer_not_registered', max_length=255)),
                ('duty_start_time', models.DateTimeField()),
                ('duty_end_time', models.DateTimeField()),
                ('department', models.CharField(blank=True, max_length=55, null=True)),
                ('rank', models.CharField(blank=True, max_length=55, null=True)),
                ('weapons', models.TextField(blank=True, null=True)),
                ('instructions', models.CharField(blank=True, max_length=200, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('police_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='police_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'BandobasOfficer',
            },
        ),
        migrations.CreateModel(
            name='PhoneOtp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=14)),
                ('otp', models.PositiveIntegerField()),
                ('session_attempts', models.PositiveIntegerField(default=0)),
                ('lifetime_attempts', models.PositiveIntegerField(default=0)),
                ('limit_attempts', models.PositiveIntegerField(default=20)),
                ('first_attempt', models.DateTimeField(default=django.utils.timezone.now)),
                ('latest_attempt', models.DateTimeField()),
            ],
            options={
                'db_table': 'PhoneOtp',
            },
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BandobasOfficerLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('altitude', models.CharField(blank=True, max_length=50, null=True)),
                ('location_accuracy', models.CharField(blank=True, max_length=50, null=True)),
                ('speed', models.CharField(blank=True, max_length=50, null=True)),
                ('distance_from_nfc_device', models.FloatField(blank=True, null=True)),
                ('is_point_inside_polygon', models.BooleanField(default=False)),
                ('client_timestamp', models.DateTimeField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('is_moving', models.CharField(blank=True, max_length=50, null=True)),
                ('speed_accuracy', models.CharField(blank=True, max_length=50, null=True)),
                ('heading', models.CharField(blank=True, max_length=50, null=True)),
                ('heading_accuracy', models.CharField(blank=True, max_length=50, null=True)),
                ('ellipsoidal_altitude', models.CharField(blank=True, max_length=50, null=True)),
                ('altitude_accuracy', models.CharField(blank=True, max_length=50, null=True)),
                ('battery_level', models.CharField(blank=True, max_length=50, null=True)),
                ('battery_is_charging', models.CharField(blank=True, max_length=50, null=True)),
                ('activity_type', models.CharField(blank=True, max_length=50, null=True)),
                ('activity_confidence', models.CharField(blank=True, max_length=50, null=True)),
                ('bearing', models.CharField(blank=True, max_length=50, null=True)),
                ('officer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kavach.bandobasofficer')),
            ],
            options={
                'db_table': 'BandobasOfficerLocation',
                'get_latest_by': 'timestamp',
            },
        ),
    ]
