# Generated by Django 4.2.2 on 2023-09-23 08:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kavach', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bus_number', models.CharField(max_length=50)),
                ('type', models.CharField(blank=True, max_length=50, null=True)),
                ('fuel_type', models.CharField(blank=True, max_length=50, null=True)),
                ('max_capacity', models.IntegerField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Bus',
            },
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kavach.bus')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Trip',
            },
        ),
        migrations.CreateModel(
            name='BusLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('altitude', models.CharField(blank=True, max_length=50, null=True)),
                ('location_accuracy', models.CharField(blank=True, max_length=50, null=True)),
                ('speed', models.CharField(blank=True, max_length=50, null=True)),
                ('distance_from_nfc_device', models.FloatField(blank=True, null=True)),
                ('is_point_inside_polygon', models.BooleanField(default=False)),
                ('client_timestamp', models.DateTimeField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('is_moving', models.CharField(blank=True, max_length=50, null=True)),
                ('speed_accuracy', models.CharField(blank=True, max_length=50, null=True)),
                ('heading', models.CharField(blank=True, max_length=50, null=True)),
                ('heading_accuracy', models.CharField(blank=True, max_length=50, null=True)),
                ('ellipsoidal_altitude', models.CharField(blank=True, max_length=50, null=True)),
                ('altitude_accuracy', models.CharField(blank=True, max_length=50, null=True)),
                ('battery_level', models.CharField(blank=True, max_length=50, null=True)),
                ('battery_is_charging', models.CharField(blank=True, max_length=50, null=True)),
                ('activity_type', models.CharField(blank=True, max_length=50, null=True)),
                ('activity_confidence', models.CharField(blank=True, max_length=50, null=True)),
                ('bearing', models.CharField(blank=True, max_length=50, null=True)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kavach.trip')),
            ],
            options={
                'db_table': 'BusLocation',
                'get_latest_by': 'timestamp',
            },
        ),
    ]
