# Generated by Django 4.2.2 on 2023-09-24 05:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kavach', '0002_bus_trip_buslocation'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusStop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('geojson_data', models.JSONField()),
            ],
            options={
                'db_table': 'BusStop',
            },
        ),
        migrations.CreateModel(
            name='BusRouteStop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField()),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kavach.bus')),
                ('stop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kavach.busstop')),
            ],
            options={
                'db_table': 'BusRouteStop',
                'ordering': ['order'],
                'unique_together': {('bus', 'stop')},
            },
        ),
    ]
